### ISSUE TITLE
Exception on invalid token

### ISSUE THREAD

**Issue by centreboard** [lelandpaul/ringingroom#157]
`token_login` assumes if it receives a token then it will always be for a valid user:
https://github.com/lelandpaul/virtual-ringing-room/blob/78f0f514f684aaf9b8b7fae9ec4f0bcdce07683d/app/auth.py#L25-L28

while `check_token` will return `None` if invalid.
Which leads to

> Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\virtual-ringing-room\venv\lib\site-packages\socketio\server.py", line 674, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Development\virtual-ringing-room\venv\lib\site-packages\socketio\server.py", line 703, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Development\virtual-ringing-room\venv\lib\site-packages\flask_socketio\__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Development\virtual-ringing-room\venv\lib\site-packages\flask_socketio\__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "D:\Development\virtual-ringing-room\app\auth.py", line 28, in wrapper_listener
    login_user(user)
  File "D:\Development\virtual-ringing-room\venv\lib\site-packages\flask_login\utils.py", line 166, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'

I'm not sure what the correct response here is. In a http request I might return `401` but don't know what SocketIO should do.

**Comment by lelandpaul** [comment]
Well spotted. Hopefully showing up at a tower with an invalid Bearer token should be very rare. Did you trigger this initially through the bug mentioned in #158?

e419783 and 0060e93 add a failsafe for this that works as follows: If the user shows up with an invalid token, the server assumes that their authentication is simply stale. It then sends `s_redirect` to redirect them to `/authenticate`, with a `?next` parameter bringing them back to the tower when they're done.

**Comment by centreboard** [comment]
Yes I was initially stuck in a loop of get a new token each time and it not working.

That looks sensible, having an invalid tower id / none at all will cause most of the SocketIO listeners to throw anyway.
